### PR TITLE
add RIESelect component

### PR DESCRIPTION
**Pull request by babenzele**
I needed a select component in a project I'm working on and figured I'd do a solid and add it to this repo, I really like what you've build here.

Let me know if there's anything I could change in this commit. I chose to pass the select options as an object, but it could just as easily be passed as a list of objects like so:
```javascript
[
  { value: "1", text: "one" },
  { value: "2", text: "two" },
  { value: "3", text: "three" },
  { value: "4", text: "four" }
]
```
- could be clearer
- more typing
- can use `map` instead of `for` loop

I had to put a conditional in `RIEBase.js` since `<select>` elements don't have the function `setSelectionRange`.

### CODE REVIEW

**Comment by babenzele** [comment]
I thought about passing select options as an object and decided that was the best way to go. It's more elegant this way and also makes it easier to convert data from a database into this format.

I changed `value` to `id` because the word 'value' is already used in the code.

**Comment by babenzele** [comment]
If we don't want to edit the base class then we could redefine `selectInputText` in `RIESelect`

**Comment by KyleAMathews** [comment]
Just installed this PR and played around with it some in a site I'm building. It works just fine but I question if it's necessary? With this in-place select component you have to click it twice to edit it whereas with a normal select you need to click just once which seems more in-line with this lib's philosophy.

Thoughts? Perhaps just recommend people use a normal `<select>`.

**Comment by babenzele** [comment]
Thanks for checking out the PR!

I'd like to not see a select box when displaying the data but I'd like to see the select box when editing. Clicking twice is inconvenient, but figuring out how to open the select box on the first click would be a great future PR.

**Comment by KyleAMathews** [comment]
You can hide all the select-looking stuff with CSS so it just looks like text until you click it.

screen shot 2016-09-17 at 10 19 02 am

That's a screenshot from a current project. "purchase" is the select.

**Comment by kaivi** [comment]
Hey, sorry it took so long, It is merged and published as v 1.0.5 now!

**Comment by KyleAMathews** [comment]
To open the select immediately you can I believe just pass the click through.

**Pull request merged**
